# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20171214_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='site',
            field=models.CharField(default='Jam', max_length=32, unique=True, verbose_name='个人博客前缀'),
            preserve_default=False,
        ),
    ]
