# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20171219_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_type_id',
            field=models.IntegerField(choices=[(1, 'Python'), (2, 'Linux'), (3, 'OpenStack'), (4, 'GoLang')], default=0),
            preserve_default=False,
        ),
    ]
