# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 03:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_blog_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='articledetail',
            name='article',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='Blog.Article', verbose_name='所属文章'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articledetail',
            name='content',
            field=models.TextField(default='1', verbose_name='文章内容'),
            preserve_default=False,
        ),
    ]
