# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_auto_20171219_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_type_id',
            field=models.IntegerField(choices=[(1, 'Python'), (2, 'Django'), (3, 'Flask'), (4, '前端'), (5, '其他')], default=5),
        ),
    ]
