# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_auto_20171220_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Blog.Category', verbose_name='文章类型'),
        ),
    ]
