# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_auto_20171220_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(null=True, upload_to='img', verbose_name='头像'),
        ),
    ]
